### ISSUE TITLE
Causing random file downloads in Firefox

### ISSUE THREAD

**Issue by SlidingHorn** [libredirect/libredirect#156]
I'm not sure how or why this is happening, but libredirect is seemingly causing Firefox to download random files when loading a page that I assume are meant to be loaded in the background or part of an include or something?

e.g. Visiting various pages across the AwesomeWM website caused a "project_factoids_stats" file to be downloaded (more than once). Going to the Recipes page and following the "A step by step Guide by Epsi" link caused various files to download that may have been style sheets or something? I deleted them, so I don't remember.

Opening the pages in a private window stopped the behavior, so I started disabling addons until the behavior reliably stopped...libredirect appears to be the culprit.

I don't believe it's anything malicious going on, just some kind of handling error.

The issue began within the last 24-48 hours.

**Firefox:** 98.0.2
**Libredirect:** 1.5.9

**Comment by ManeraKai** [comment]
Does the same happen with version 1.6.0?

**Comment by ManeraKai** [comment]
The issue of downloading random files was addressed multiple times this day. I released this new version before some hours.

**Comment by SlidingHorn** [comment]
Okay - updated to 1.6, enabled, and did a cache reload on a page that was pretty consistently "serving" a random file, and it doesn't appear to be happening. I'll come back and update if it happens again.

If you don't hear from me in like 48 hours, assume all all is well

**Comment by ManeraKai** [comment]
Nice! I'll close the issue after 48 hours. Clock is ticking xD

**Comment by hellotinh03** [comment]
1.6.0 seems to fix the issue. I was having the same problem and was just going to post an issue here, then I saw this and realize that I was in 1.5.9.

**Comment by Jogai** [comment]
Dont know if its the same bug, but on 1.6 I still get a redirect after a few seconds on this page: https://www.kickstarter.com/projects/dragonsteel/surprise-four-secret-novels-by-brandon-sanderson/posts (98.0.2 (64-bit) on archlinux)
