### ISSUE TITLE
Add support for Piped Material

### ISSUE THREAD

**Issue by mmjee** [libredirect/libredirect#51]
DISCLAIMER: I'm the sole developer of Piped Material, but I think users will appreciate this feature and at least one user has asked for this.

Piped Material is a fork off Piped, with a few advantages. It'll be nice to see it as an option beside Piped. It uses the same API as Piped and therefore instances, but not the frontends.

There's a grid of frontend instances in the repo below, I'd recommend only adding the production instance for now.

URL: https://github.com/mmjee/Piped-Material

**Comment by IronMaltese** [comment]
Piped is working on a redesign at [](https://ui-v2.piped.pages.dev/) which is very similar to piped material, I’m really indifferent towards this issue, but just wanted to throw that in here

**Comment by mmjee** [comment]
Indeed, I'm aware of that. However PM has some irreconcilable and systematic changes that do make it a descendant but not a drop-in replacement for Piped. UI-v2 is just a redesign, which unfortunately also seems to be somewhat dead in the water. It's also not very Material Design.
Perhaps I should consider changing the name to something totally different.

Regards,

**Comment by ManeraKai** [comment]
Interesting, why didn't you create some pull requests though? Piped is still a new project for it to be forked and is still worked on everyday.

**Comment by mmjee** [comment]
Too many things. There is deep philosophical disconnect between Piped and PM, since PM takes a radically different approach to the design, Vue 2 vs Vue 3, structural issues. I don't think Kavin would want to maintain it. I wouldn't want to force it either.

Regards,

**Comment by stephenhawk8054** [comment]
Hi, the project looks nice, but somehow I can't see 1080p options, even after adjusting the preferences?

For example:
[https://piped-material.ftp.sh/watch?v=mk48xRzuNvA](https://piped-material.ftp.sh/watch?v=mk48xRzuNvA)

![image](https://user-images.githubusercontent.com/66517106/154828928-4d31cc3a-5a60-41ac-bec1-df58abdcf27f.png)

While I can in `piped.kavin.rocks`

![image](https://user-images.githubusercontent.com/66517106/154828934-da3a8837-14e4-4ed6-adff-55917c1aa0ce.png)

**Comment by mmjee** [comment]
[**@stephenhawk8054**](https://github.com/stephenhawk8054) commented on [20 Feb 2022, 10:25 am IST](https://github.com/libredirect/libredirect/issues/51#issuecomment-1046163236 "2022-02-20T04:55:57Z - Replied by Github Reply Comments"):
> Hi, the project looks nice, but somehow I can't see 1080p options, even after adjusting the preferences?
> 
> For example:  
> [https://piped-material.ftp.sh/watch?v=mk48xRzuNvA](https://piped-material.ftp.sh/watch?v=mk48xRzuNvA)
> 
> [![image](https://user-images.githubusercontent.com/66517106/154828928-4d31cc3a-5a60-41ac-bec1-df58abdcf27f.png)](https://user-images.githubusercontent.com/66517106/154828928-4d31cc3a-5a60-41ac-bec1-df58abdcf27f.png)
> 
> While I can in `piped.kavin.rocks`
> 
> [![image](https://user-images.githubusercontent.com/66517106/154828934-da3a8837-14e4-4ed6-adff-55917c1aa0ce.png)](https://user-images.githubusercontent.com/66517106/154828934-da3a8837-14e4-4ed6-adff-55917c1aa0ce.png)

![image](https://user-images.githubusercontent.com/29047033/154844195-078b2a43-32cb-4448-bb10-70e0ec6dcdee.png)
I don't see 1080p either, under the hood both Piped and PM have almost the same code handling playing videos, so if it reproduces, should be an easy fix.

**Comment by ManeraKai** [comment]
Can't seem to successfully add custom settings. I'll try to work on that more. But it's working!!

**Comment by mmjee** [comment]
Custom settings may require a patch, is it possible to release without custom settings? I'll let you know when it's fixed though.

Regards,

**Comment by ManeraKai** [comment]
Yeah np

**Comment by Loki-L1130** [comment]
Well, It seems broken in terms of Redirects in the Latest Commits

**Comment by mmjee** [comment]
What does redirect entail here exactly? Just curious.

Regards,

**Comment by Loki-L1130** [comment]
Well, When choosing Piped Material to redirect youtube. It doesn't redirect and still goes to youtube.com

**Comment by ManeraKai** [comment]
@Loki-L1130 I didn't release a new version it yet.

**Comment by ManeraKai** [comment]
Released a new version. Everything should work now.

**Comment by mmjee** [comment]
I think I received the update, but redirects definitely don't work and I don't see a list of Piped Material instances.

Regards,

**Comment by ManeraKai** [comment]
1.4.8?

**Comment by mmjee** [comment]
I removed and reinstalled the addon and it seems to work now. But I think I still received the update since I saw the Piped Material option which was only recently introduced with 1.4.8, right?
My guess is if I'm right something broke during the migration.

Regards,

**Comment by ManeraKai** [comment]
I added the option at 1.4.7 I think and enabled it's function on 1.4.8. Can you show me a picture of what's happening.
What does the console in this url says to you: `about:devtools-toolbox?id=7esoorv3%40alefvanoon.anonaddy.me&type=extension`

**Comment by mmjee** [comment]
Since I reinstalled it, it seems to be working fine. Nothing interesting except youtu.be -> PM redirects.

Regards,

**Comment by ManeraKai** [comment]
> youtu.be -> PM redirects.

?

**Comment by mmjee** [comment]
PM = Piped Material.

Regards,

**Comment by ManeraKai** [comment]
I know but what's wrong with youtu.be?

**Comment by mmjee** [comment]
Err I actually meant it contains nothing but youtu.be -> PM redirects. Eitherway it works fine.

Regards,

**Comment by ManeraKai** [comment]
I'll close the issue as it's has been added. I'll work on the parameters problem more in the future.
