### ISSUE TITLE
LibRedirect exceptions do not work on chromium based browsers

### ISSUE THREAD

**Issue by sitiom** [libredirect/libredirect#53]
The Google homepage is not a search query and thus should not be redirected, much like how privacy redirect does it.

**Comment by ManeraKai** [comment]
The site (google.com) is dynamic and I won't trust it's interface. I much more trust the front-ends of Whoogle and SearX. That's why I changed it.

**Comment by sitiom** [comment]
At least provide an option not to redirect it. I would like to be able to access the account switcher and the app list on the top right of the homepage.

**Comment by ManeraKai** [comment]
There's an exception list in the settings page.

**Comment by sitiom** [comment]
Doesn't work, it still redirects me. I assume this is a bug?
![image](https://user-images.githubusercontent.com/56180050/154885075-3a222a4e-a079-4eba-9b7b-85669ca24540.png)

**Comment by ManeraKai** [comment]
yep, will fix it this day.

**Comment by ManeraKai** [comment]
Turns out it's not a bug, you should add `https://google.com` and `https://www.google.com`.
or this Regex: `https?:\/\/(www\.|)google\.com`.

**Comment by sitiom** [comment]
Thanks, adding `https://google.com` and `https://www.google.com` didn't work but adding `https?:\/\/(www\.|)google\.com` did.

**Comment by ManeraKai** [comment]
Be aware that the Regex will accept everything in that domain name. I mean even searches and not just the home page.
I'll write a better one for you.

**Comment by ManeraKai** [comment]
`https?:\/\/(www\.|)google\.com(\/|$)`

**Comment by sitiom** [comment]
> Be aware that the Regex will accept everything in that domain name. I mean even searches and not just the home page. I'll write a better one for you.

I seem to have missed that, but `https?:\/\/(www\.|)google\.com(\/|$)` doesn't seem to work as well.

Any pointers to why the `https://google.com` and `https://www.google.com` URL method doesn't work?

**Comment by ManeraKai** [comment]
Try to update the version. I've released 1.4 this day and it was working.

**Comment by sitiom** [comment]
I'm using brave and already pulled to the latest commit.

**Comment by ManeraKai** [comment]
I can't test chromium browsers now as I'm using my phone. I'll see whats the problem once I return home 👍

**Comment by sitiom** [comment]
Renamed the issue. Can you reopen this issue as this is not yet resolved?

**Comment by ManeraKai** [comment]
I'm now in home and test it on chromium. btw I'm using version [1.4.1](https://github.com/libredirect/libredirect/releases/tag/1.4.1). Installed the `.crx` file, and it's working fine with the `url` and `regex` way.

**Comment by sitiom** [comment]
Still the same thing, I tried both the `.zip` and from the repo directly (can't try `.crx` because I'm on brave). Is this some brave issue?

**Comment by sitiom** [comment]
Weird, I even get it in a fresh brave install with only libredirect installed:


https://user-images.githubusercontent.com/56180050/155634150-ff3331e5-9b9d-4fdc-8344-680d648a921e.mp4

**Comment by ManeraKai** [comment]
wait. It maybe because you google domain name is different or has a subdomain like `https://google.com.tr`

**Comment by sitiom** [comment]
Clearly, I typed `google.com` and the search query showed `google.com`.

**Comment by ManeraKai** [comment]
Click this to inspect. It will tell you the original url and the new url that will be redirected to:
![image](https://user-images.githubusercontent.com/40805353/155740304-80abbc1c-a240-4c23-946f-9a7f007594f0.png)

**Comment by ManeraKai** [comment]
It says `http` not `https` try to add `http://google.com` and `http://www.google.com` too. The regex is much easier imo.

**Comment by sitiom** [comment]
Hmm, regex seems to be working now; I'll use that. Thanks for your help!
